### PR TITLE
prepare stevedore packages

### PR DESCRIPTION
**Pull request by mostynb**
This changes the artifacts to be in a form suitable for use with stevedore.

### CODE REVIEW

**Comment by mostynb** [comment]
@KernalPanik: this has been approved by legal, and is now ready for review- please take a look.

**Review by KasparasKralikas — APPROVED** [review]
Approving 👍 but would like to see Lukaš review on this too, and see the changes for Qt.jam.cs so we can fully test it and land the changes together.

**Review by KernalPanik — APPROVED** [review]

**Comment by mostynb** [comment]
Corresponding editor PR: https://github.cds.internal.unity3d.com/unity/unity/pull/2996

**Comment by KasparasKralikas** [comment]
We can land this

**Pull request merged**
